name: 'GitHub CI'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-node:
    name: Test on Node.js v${{ matrix.node-version }} and jest v${{ matrix.jest-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
      - run: yarn test:coverage

  test-os:
    name: Test on ${{ matrix.os }} using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn install
      - run: yarn test:coverage

  lint:
    name: Run ESLint 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn install
      - run: yarn lint
